<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * Homestretch implementation : © <Your name here> <Your email address here>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * Homestretch game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */


/*

Example:

$this->card_types = array(
    1 => array( "card_name" => ...,
                ...
              )
);

*/
$this->colors = array(
    1 => array( 'name' => self::_('red'), 'namectr' => clienttranslate( 'red' ) ),
    2 => array( 'name' => self::_('blue'), 'namectr' => clienttranslate( 'blue' ) ),
);
$this->DiceCount = 2;
$this->horse_types  = array(
    1 => array( 'name' => clienttranslate('Horse 2'),
        'nametr' => self::_('2'),
        'handicap' => 0,
        'salary' => 2000,
        'position' => 1,
    ),
    2 => array( 'name' => clienttranslate('Horse 3'),
        'nametr' => self::_('3'),
        'handicap' => 0,
        'salary' => 4000,
        'position' => 1,
    ),
    3 => array( 'name' => clienttranslate('Horse 4'),
        'nametr' => self::_('4'),
        'handicap' => 0,
        'salary' => 6000,
        'position' => 1,
    ),
    4 => array( 'name' => clienttranslate('Horse 5'),
        'nametr' => self::_('5'),
        'handicap' => 0,
        'salary' => 8000,
        'position' => 1,
    ),
    5 => array( 'name' => clienttranslate('Horse 6'),
        'nametr' => self::_('6'),
        'handicap' => 0,
        'salary' => 10000,
        'position' => 1,
    ),
    6 => array( 'name' => clienttranslate('Horse 7'),
        'nametr' => self::_('7'),
        'handicap' => 0,
        'salary' => 10000,
        'position' => 1,
    ),
    7 => array( 'name' => clienttranslate('Horse 8'),
        'nametr' => self::_('8'),
        'handicap' => 0,
        'salary' => 10000,
        'position' => 1,
    ),
    8 => array( 'name' => clienttranslate('Horse 9'),
        'nametr' => self::_('9'),
        'handicap' => 0,
        'salary' => 8000,
        'position' => 1,
    ),
    9 => array( 'name' => clienttranslate('Horse 10'),
        'nametr' => self::_('10'),
        'handicap' => 0,
        'salary' => 6000,
        'position' => 1,
    ),
    10 => array( 'name' => clienttranslate('Horse 11'),
        'nametr' => self::_('11'),
        'handicap' => 0,
        'salary' => 4000,
        'position' => 1,
    ),
    11 => array( 'name' => clienttranslate('Horse 12'),
        'nametr' => self::_('12'),
        'handicap' => 0,
        'salary' => 2000,
        'position' => 1,
    ),
);

$this->race_cards  = array(
    1 => array( 'name' => clienttranslate('Asbury Downs'),
        'nametr' => self::_('2'),
        'handicap_x1' => 6,
        'handicap_x2' => 7,
        'handicap_x3' => 8,
        'minus_two1' => 9,
        'minus_two2' => 0,
        'plus_four1' => 0,
        'plus_four2' => 0,
        'plus_six1' => 4,
        'plus_six2' => 10,
        'win' => 18,
        'place' => 12,
        'show' => 6,
    ),
    2 => array( 'name' => clienttranslate('Atchafalava Fair'),
        'nametr' => self::_('3'),
        'handicap_x1' => 6,
        'handicap_x2' => 7,
        'handicap_x3' => 8,
        'minus_two1' => 5,
        'minus_two2' => 0,
        'plus_four1' => 9,
        'plus_four2' => 10,
        'plus_six1' => 0,
        'plus_six2' => 0,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    3 => array( 'name' => clienttranslate('Beantown Downs'),
        'nametr' => self::_('4'),
        'handicap_x1' => 6,
        'handicap_x2' => 7,
        'handicap_x3' => 0,
        'minus_two1' => 0,
        'minus_two2' => 0,
        'plus_four1' => 10,
        'plus_four2' => 0,
        'plus_six1' => 2,
        'plus_six2' => 3,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    4 => array( 'name' => clienttranslate('Cuyoga Park'),
        'nametr' => self::_('5'),
        'handicap_x1' => 6,
        'handicap_x2' => 8,
        'handicap_x3' => 0,
        'minus_two1' => 3,
        'minus_two2' => 0,
        'plus_four1' => 9,
        'plus_four2' => 0,
        'plus_six1' => 2,
        'plus_six2' => 12,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    5 => array( 'name' => clienttranslate('Elk Grove'),
        'nametr' => self::_('5'),
        'handicap_x1' => 6,
        'handicap_x2' => 8,
        'handicap_x3' => 0,
        'minus_two1' => 0,
        'minus_two2' => 0,
        'plus_four1' => 4,
        'plus_four2' => 0,
        'plus_six1' => 11,
        'plus_six2' => 12,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    6 => array( 'name' => clienttranslate('Liberty Downs'),
        'nametr' => self::_('5'),
        'handicap_x1' => 6,
        'handicap_x2' => 7,
        'handicap_x3' => 8,
        'minus_two1' => 9,
        'minus_two2' => 0,
        'plus_four1' => 10,
        'plus_four2' => 0,
        'plus_six1' => 4,
        'plus_six2' => 0,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    7 => array( 'name' => clienttranslate('White River Downs'),
        'nametr' => self::_('6'),
        'handicap_x1' => 7,
        'handicap_x2' => 0,
        'handicap_x3' => 0,
        'minus_two1' => 11,
        'minus_two2' => 0,
        'plus_four1' => 4,
        'plus_four2' => 10,
        'plus_six1' => 12,
        'plus_six2' => 0,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    8 => array( 'name' => clienttranslate('White Mountain Downs'),
        'nametr' => self::_('7'),
        'handicap_x1' => 0,
        'handicap_x2' => 0,
        'handicap_x3' => 0,
        'minus_two1' => 0,
        'minus_two2' => 0,
        'plus_four1' => 0,
        'plus_four2' => 0,
        'plus_six1' => 0,
        'plus_six2' => 0,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    9 => array( 'name' => clienttranslate('Tarpon Bay Downs'),
        'nametr' => self::_('8'),
        'handicap_x1' => 7,
        'handicap_x2' => 0,
        'handicap_x3' => 0,
        'minus_two1' => 5,
        'minus_two2' => 0,
        'plus_four1' => 12,
        'plus_four2' => 0,
        'plus_six1' => 3,
        'plus_six2' => 0,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    10 => array( 'name' => clienttranslate('Prairie Downs'),
        'nametr' => self::_('9'),
        'handicap_x1' => 6,
        'handicap_x2' => 0,
        'handicap_x3' => 0,
        'minus_two1' => 9,
        'minus_two2' => 0,
        'plus_four1' => 5,
        'plus_four2' => 0,
        'plus_six1' => 3,
        'plus_six2' => 11,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    11 => array( 'name' => clienttranslate('Moose Meadows'),
        'nametr' => self::_('9'),
        'handicap_x1' => 6,
        'handicap_x2' => 0,
        'handicap_x3' => 0,
        'minus_two1' => 90,
        'minus_two2' => 0,
        'plus_four1' => 5,
        'plus_four2' => 0,
        'plus_six1' => 2,
        'plus_six2' => 11,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
    12 => array( 'name' => clienttranslate('Prairie Downs'),
        'nametr' => self::_('9'),
        'handicap_x1' => 7,
        'handicap_x2' => 8,
        'handicap_x3' => 0,
        'minus_two1' => 0,
        'minus_two2' => 0,
        'plus_four1' => 5,
        'plus_four2' => 0,
        'plus_six1' => 2,
        'plus_six2' => 12,
        'win' => 0,
        'place' => 0,
        'show' => 0,
    ),
);



